# Note for forks: Azure Pipelines is triggered only by commits to the branches
# matching the patterns below.
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers
trigger:
  - master
  - ci-*

jobs:

  - job: Windows_vs2019
    pool:
      vmImage: windows-2019
    steps:
      - template: ci/azure-steps.yml
    strategy:
      matrix:
        x86_64-msvc:
          TARGET: x86_64-pc-windows-msvc

  - job: Windows_vs2017
    pool:
      vmImage: vs2017-win2016
    steps:
      - template: ci/azure-steps.yml
    strategy:
      matrix:
        x86_64-msvc:
          TARGET: x86_64-pc-windows-msvc
        i686-msvc:
          TARGET: i686-pc-windows-msvc
        x86_64-gnu:
          TARGET: x86_64-pc-windows-gnu
        i686-gnu:
          TARGET: i686-pc-windows-gnu

  - job: Windows_vs2015
    pool:
      vmImage: vs2015-win2012r2
    steps:
      - template: ci/azure-steps.yml
    strategy:
      matrix:
        x86_64-msvc:
          TARGET: x86_64-pc-windows-msvc
        i686-msvc:
          TARGET: i686-pc-windows-msvc
