jobs:

  - job: Windows_vs2017
    pool:
      vmImage: vs2017-win2016
    steps:
      - template: ci/azure-steps.yml
    strategy:
      matrix:
        x86_64-gnu:
          ARCH: x86_64
          BITS: 64
          TARGET: x86_64-pc-windows-gnu
        i686-gnu:
          ARCH: i686
          BITS: 32
          TARGET: i686-pc-windows-gnu
